# Generated by Django 3.1.7 on 2021-03-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210305_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='User',
        ),
    ]
